
[functions.push-confirmed]
enabled = true
verify_jwt = true
import_map = "./functions/push-confirmed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-confirmed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-confirmed/*.html" ]

[functions.push-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/push-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-reminders/*.html" ]

[functions.dispatch-notifs]
enabled = true
verify_jwt = false
entrypoint = "./functions/dispatch-notifs/index.ts"

[functions.record-match-result]
enabled = true
verify_jwt = true
entrypoint = "./functions/record-match-result/index.ts"

[functions.evaluate-badges]
enabled = true
verify_jwt = false
entrypoint = "./functions/evaluate-badges/index.ts"

[functions.update-match-ratings]
enabled = true
verify_jwt = false
entrypoint = "./functions/update-match-ratings/index.ts"
